# fly.toml app configuration file generated for withered-silence-1660 on 2023-06-15T22:30:01+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "withered-silence-1660"
primary_region = "ams"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
